import Foundation

enum WordMatchLibrary {
    static let primerSet: [WordMatchPair] = [
        WordMatchPair(key: "beads", word: "БУСЫ", illustration: .asset(name: "WordBeads")),
        WordMatchPair(key: "bucket", word: "ВЕДРО", illustration: .asset(name: "WordBucket")),
        WordMatchPair(key: "bread", word: "БУЛКА", illustration: .asset(name: "WordBread")),
        WordMatchPair(key: "bag", word: "СУМКА", illustration: .asset(name: "WordBag")),
        WordMatchPair(key: "doll", word: "КУКЛА", illustration: .asset(name: "WordDoll"))
    ]

    static let extendedSet: [WordMatchPair] = [
        WordMatchPair(key: "cat", word: "КОТ", illustration: .bundlePNG(name: "cat")),
        WordMatchPair(key: "dog", word: "ПЁС", illustration: .bundlePNG(name: "dog")),
        WordMatchPair(key: "hedgehog", word: "ЁЖ", illustration: .bundlePNG(name: "hedgehog")),
        WordMatchPair(key: "beetle", word: "ЖУК", illustration: .bundlePNG(name: "beetle")),
        WordMatchPair(key: "crayfish", word: "РАК", illustration: .bundlePNG(name: "crayfish")),
        WordMatchPair(key: "owl", word: "СОВА", illustration: .bundlePNG(name: "owl")),
        WordMatchPair(key: "fox", word: "ЛИСА", illustration: .bundlePNG(name: "fox")),
        WordMatchPair(key: "hare", word: "ЗАЯЦ", illustration: .bundlePNG(name: "hare")),
        WordMatchPair(key: "goat", word: "КОЗА", illustration: .bundlePNG(name: "goat")),
        WordMatchPair(key: "elephant", word: "СЛОН", illustration: .bundlePNG(name: "elephant")),

        WordMatchPair(key: "apple", word: "ЯБЛОКО", illustration: .bundlePNG(name: "apple")),
        WordMatchPair(key: "pear", word: "ГРУША", illustration: .bundlePNG(name: "pear")),
        WordMatchPair(key: "plum", word: "СЛИВА", illustration: .bundlePNG(name: "plum")),
        WordMatchPair(key: "lemon", word: "ЛИМОН", illustration: .bundlePNG(name: "lemon")),
        WordMatchPair(key: "watermelon", word: "АРБУЗ", illustration: .bundlePNG(name: "watermelon")),
        WordMatchPair(key: "melon", word: "ДЫНЯ", illustration: .bundlePNG(name: "melon")),
        WordMatchPair(key: "banana", word: "БАНАН", illustration: .bundlePNG(name: "banana")),
        WordMatchPair(key: "cherry", word: "ВИШНЯ", illustration: .bundlePNG(name: "cherry")),
        WordMatchPair(key: "carrot", word: "МОРКОВЬ", illustration: .bundlePNG(name: "carrot")),
        WordMatchPair(key: "cucumber", word: "ОГУРЕЦ", illustration: .bundlePNG(name: "cucumber")),

        WordMatchPair(key: "car", word: "МАШИНА", illustration: .bundlePNG(name: "car")),
        WordMatchPair(key: "bus", word: "АВТОБУС", illustration: .bundlePNG(name: "bus")),
        WordMatchPair(key: "rocket", word: "РАКЕТА", illustration: .bundlePNG(name: "rocket")),
        WordMatchPair(key: "train", word: "ПОЕЗД", illustration: .bundlePNG(name: "train")),
        WordMatchPair(key: "boat", word: "ЛОДКА", illustration: .bundlePNG(name: "boat")),
        WordMatchPair(key: "airplane", word: "САМОЛЕТ", illustration: .bundlePNG(name: "airplane")),
        WordMatchPair(key: "tractor", word: "ТРАКТОР", illustration: .bundlePNG(name: "tractor")),
        WordMatchPair(key: "ship", word: "КОРАБЛЬ", illustration: .bundlePNG(name: "ship")),
        WordMatchPair(key: "tram", word: "ТРАМВАЙ", illustration: .bundlePNG(name: "tram")),
        WordMatchPair(key: "bicycle", word: "ВЕЛОСИПЕД", illustration: .bundlePNG(name: "bicycle")),

        WordMatchPair(key: "house", word: "ДОМ", illustration: .bundlePNG(name: "house")),
        WordMatchPair(key: "ball", word: "МЯЧ", illustration: .bundlePNG(name: "ball")),
        WordMatchPair(key: "balloon", word: "ШАР", illustration: .bundlePNG(name: "balloon")),
        WordMatchPair(key: "cube", word: "КУБИК", illustration: .bundlePNG(name: "cube")),
        WordMatchPair(key: "spinning-top", word: "ЮЛА", illustration: .bundlePNG(name: "spinning-top")),
        WordMatchPair(key: "teddy-bear", word: "МИШКА", illustration: .bundlePNG(name: "teddy-bear")),
        WordMatchPair(key: "robot", word: "РОБОТ", illustration: .bundlePNG(name: "robot")),
        WordMatchPair(key: "sled", word: "САНКИ", illustration: .bundlePNG(name: "sled")),
        WordMatchPair(key: "scooter", word: "САМОКАТ", illustration: .bundlePNG(name: "scooter")),
        WordMatchPair(key: "stacking-rings", word: "ПИРАМИДКА", illustration: .bundlePNG(name: "stacking-rings")),

        WordMatchPair(key: "cup", word: "ЧАШКА", illustration: .bundlePNG(name: "cup")),
        WordMatchPair(key: "spoon", word: "ЛОЖКА", illustration: .bundlePNG(name: "spoon")),
        WordMatchPair(key: "fork", word: "ВИЛКА", illustration: .bundlePNG(name: "fork")),
        WordMatchPair(key: "plate", word: "ТАРЕЛКА", illustration: .bundlePNG(name: "plate")),
        WordMatchPair(key: "teapot", word: "ЧАЙНИК", illustration: .bundlePNG(name: "teapot")),
        WordMatchPair(key: "scissors", word: "НОЖНИЦЫ", illustration: .bundlePNG(name: "scissors")),
        WordMatchPair(key: "hammer", word: "МОЛОТОК", illustration: .bundlePNG(name: "hammer")),
        WordMatchPair(key: "watering-can", word: "ЛЕЙКА", illustration: .bundlePNG(name: "watering-can")),
        WordMatchPair(key: "umbrella", word: "ЗОНТ", illustration: .bundlePNG(name: "umbrella")),
        WordMatchPair(key: "clock", word: "ЧАСЫ", illustration: .bundlePNG(name: "clock")),

        WordMatchPair(key: "book", word: "КНИГА", illustration: .bundlePNG(name: "book")),
        WordMatchPair(key: "paint-set", word: "КРАСКИ", illustration: .bundlePNG(name: "paint-set")),
        WordMatchPair(key: "paintbrush", word: "КИСТЬ", illustration: .bundlePNG(name: "paintbrush")),
        WordMatchPair(key: "pen", word: "РУЧКА", illustration: .bundlePNG(name: "pen")),
        WordMatchPair(key: "pencil", word: "КАРАНДАШ", illustration: .bundlePNG(name: "pencil")),
        WordMatchPair(key: "notebook", word: "ТЕТРАДЬ", illustration: .bundlePNG(name: "notebook")),
        WordMatchPair(key: "palette", word: "ПАЛИТРА", illustration: .bundlePNG(name: "palette")),
        WordMatchPair(key: "backpack", word: "РЮКЗАК", illustration: .bundlePNG(name: "backpack")),
        WordMatchPair(key: "ruler", word: "ЛИНЕЙКА", illustration: .bundlePNG(name: "ruler")),
        WordMatchPair(key: "globe", word: "ГЛОБУС", illustration: .bundlePNG(name: "globe")),

        WordMatchPair(key: "hat", word: "ШАПКА", illustration: .bundlePNG(name: "hat")),
        WordMatchPair(key: "scarf", word: "ШАРФ", illustration: .bundlePNG(name: "scarf")),
        WordMatchPair(key: "socks", word: "НОСКИ", illustration: .bundlePNG(name: "socks")),
        WordMatchPair(key: "boots", word: "БОТИНКИ", illustration: .bundlePNG(name: "boots")),
        WordMatchPair(key: "dress", word: "ПЛАТЬЕ", illustration: .bundlePNG(name: "dress")),
        WordMatchPair(key: "skirt", word: "ЮБКА", illustration: .bundlePNG(name: "skirt")),
        WordMatchPair(key: "sweater", word: "КОФТА", illustration: .bundlePNG(name: "sweater")),
        WordMatchPair(key: "mittens", word: "ВАРЕЖКИ", illustration: .bundlePNG(name: "mittens")),
        WordMatchPair(key: "shorts", word: "ШОРТЫ", illustration: .bundlePNG(name: "shorts")),
        WordMatchPair(key: "rain-boots", word: "САПОГИ", illustration: .bundlePNG(name: "rain-boots")),

        WordMatchPair(key: "flower", word: "ЦВЕТОК", illustration: .bundlePNG(name: "flower")),
        WordMatchPair(key: "tree", word: "ДЕРЕВО", illustration: .bundlePNG(name: "tree")),
        WordMatchPair(key: "mushroom", word: "ГРИБ", illustration: .bundlePNG(name: "mushroom")),
        WordMatchPair(key: "leaf", word: "ЛИСТ", illustration: .bundlePNG(name: "leaf")),
        WordMatchPair(key: "cloud", word: "ТУЧА", illustration: .bundlePNG(name: "cloud")),
        WordMatchPair(key: "sun", word: "СОЛНЦЕ", illustration: .bundlePNG(name: "sun")),
        WordMatchPair(key: "moon", word: "ЛУНА", illustration: .bundlePNG(name: "moon")),
        WordMatchPair(key: "star", word: "ЗВЕЗДА", illustration: .bundlePNG(name: "star")),
        WordMatchPair(key: "rainbow", word: "РАДУГА", illustration: .bundlePNG(name: "rainbow")),
        WordMatchPair(key: "snowman", word: "СНЕГОВИК", illustration: .bundlePNG(name: "snowman")),

        WordMatchPair(key: "juice", word: "СОК", illustration: .bundlePNG(name: "juice")),
        WordMatchPair(key: "cake", word: "ТОРТ", illustration: .bundlePNG(name: "cake")),
        WordMatchPair(key: "onion", word: "ЛУК", illustration: .bundlePNG(name: "onion")),
        WordMatchPair(key: "cheese", word: "СЫР", illustration: .bundlePNG(name: "cheese")),
        WordMatchPair(key: "soup", word: "СУП", illustration: .bundlePNG(name: "soup")),
        WordMatchPair(key: "porridge", word: "КАША", illustration: .bundlePNG(name: "porridge")),
        WordMatchPair(key: "milk", word: "МОЛОКО", illustration: .bundlePNG(name: "milk")),
        WordMatchPair(key: "candy", word: "КОНФЕТА", illustration: .bundlePNG(name: "candy")),
        WordMatchPair(key: "ice-cream", word: "МОРОЖЕНОЕ", illustration: .bundlePNG(name: "ice-cream")),
        WordMatchPair(key: "cookie", word: "ПЕЧЕНЬЕ", illustration: .bundlePNG(name: "cookie")),

        WordMatchPair(key: "drum", word: "БАРАБАН", illustration: .bundlePNG(name: "drum")),
        WordMatchPair(key: "flute", word: "ДУДКА", illustration: .bundlePNG(name: "flute")),
        WordMatchPair(key: "flag", word: "ФЛАГ", illustration: .bundlePNG(name: "flag")),
        WordMatchPair(key: "key", word: "КЛЮЧ", illustration: .bundlePNG(name: "key")),
        WordMatchPair(key: "padlock", word: "ЗАМОК", illustration: .bundlePNG(name: "padlock")),
        WordMatchPair(key: "candle", word: "СВЕЧА", illustration: .bundlePNG(name: "candle")),
        WordMatchPair(key: "bed", word: "КРОВАТЬ", illustration: .bundlePNG(name: "bed")),
        WordMatchPair(key: "pillow", word: "ПОДУШКА", illustration: .bundlePNG(name: "pillow")),
        WordMatchPair(key: "soap", word: "МЫЛО", illustration: .bundlePNG(name: "soap")),
        WordMatchPair(key: "brush", word: "ЩЕТКА", illustration: .bundlePNG(name: "brush"))
    ]

    static let supplementalSet: [WordMatchPair] = [
        WordMatchPair(key: "duck", word: "УТКА", illustration: .bundlePNG(name: "duck")),
        WordMatchPair(key: "goose", word: "ГУСЬ", illustration: .bundlePNG(name: "goose")),
        WordMatchPair(key: "rooster", word: "ПЕТУХ", illustration: .bundlePNG(name: "rooster")),
        WordMatchPair(key: "hen", word: "КУРИЦА", illustration: .bundlePNG(name: "hen")),
        WordMatchPair(key: "turkey", word: "ИНДЮК", illustration: .bundlePNG(name: "turkey")),
        WordMatchPair(key: "pigeon", word: "ГОЛУБЬ", illustration: .bundlePNG(name: "pigeon")),
        WordMatchPair(key: "crow", word: "ВОРОНА", illustration: .bundlePNG(name: "crow")),
        WordMatchPair(key: "parrot", word: "ПОПУГАЙ", illustration: .bundlePNG(name: "parrot")),
        WordMatchPair(key: "swan", word: "ЛЕБЕДЬ", illustration: .bundlePNG(name: "swan")),
        WordMatchPair(key: "crane", word: "ЖУРАВЛЬ", illustration: .bundlePNG(name: "crane")),

        WordMatchPair(key: "fish", word: "РЫБА", illustration: .bundlePNG(name: "fish")),
        WordMatchPair(key: "whale", word: "КИТ", illustration: .bundlePNG(name: "whale")),
        WordMatchPair(key: "dolphin", word: "ДЕЛЬФИН", illustration: .bundlePNG(name: "dolphin")),
        WordMatchPair(key: "shark", word: "АКУЛА", illustration: .bundlePNG(name: "shark")),
        WordMatchPair(key: "octopus", word: "ОСЬМИНОГ", illustration: .bundlePNG(name: "octopus")),
        WordMatchPair(key: "crab", word: "КРАБ", illustration: .bundlePNG(name: "crab")),
        WordMatchPair(key: "jellyfish", word: "МЕДУЗА", illustration: .bundlePNG(name: "jellyfish")),
        WordMatchPair(key: "walrus", word: "МОРЖ", illustration: .bundlePNG(name: "walrus")),
        WordMatchPair(key: "seal", word: "ТЮЛЕНЬ", illustration: .bundlePNG(name: "seal")),
        WordMatchPair(key: "turtle", word: "ЧЕРЕПАХА", illustration: .bundlePNG(name: "turtle")),

        WordMatchPair(key: "horse", word: "ЛОШАДЬ", illustration: .bundlePNG(name: "horse")),
        WordMatchPair(key: "camel", word: "ВЕРБЛЮД", illustration: .bundlePNG(name: "camel")),
        WordMatchPair(key: "zebra", word: "ЗЕБРА", illustration: .bundlePNG(name: "zebra")),
        WordMatchPair(key: "giraffe", word: "ЖИРАФ", illustration: .bundlePNG(name: "giraffe")),
        WordMatchPair(key: "monkey", word: "ОБЕЗЬЯНА", illustration: .bundlePNG(name: "monkey")),
        WordMatchPair(key: "deer", word: "ОЛЕНЬ", illustration: .bundlePNG(name: "deer")),
        WordMatchPair(key: "bear", word: "МЕДВЕДЬ", illustration: .bundlePNG(name: "bear")),
        WordMatchPair(key: "wolf", word: "ВОЛК", illustration: .bundlePNG(name: "wolf")),
        WordMatchPair(key: "squirrel", word: "БЕЛКА", illustration: .bundlePNG(name: "squirrel")),
        WordMatchPair(key: "pig", word: "СВИНЬЯ", illustration: .bundlePNG(name: "pig")),

        WordMatchPair(key: "butterfly", word: "БАБОЧКА", illustration: .bundlePNG(name: "butterfly")),
        WordMatchPair(key: "bee", word: "ПЧЕЛА", illustration: .bundlePNG(name: "bee")),
        WordMatchPair(key: "ant", word: "МУРАВЕЙ", illustration: .bundlePNG(name: "ant")),
        WordMatchPair(key: "dragonfly", word: "СТРЕКОЗА", illustration: .bundlePNG(name: "dragonfly")),
        WordMatchPair(key: "snail", word: "УЛИТКА", illustration: .bundlePNG(name: "snail")),
        WordMatchPair(key: "spider", word: "ПАУК", illustration: .bundlePNG(name: "spider")),
        WordMatchPair(key: "grasshopper", word: "КУЗНЕЧИК", illustration: .bundlePNG(name: "grasshopper")),
        WordMatchPair(key: "caterpillar", word: "ГУСЕНИЦА", illustration: .bundlePNG(name: "caterpillar")),
        WordMatchPair(key: "mosquito", word: "КОМАР", illustration: .bundlePNG(name: "mosquito")),
        WordMatchPair(key: "moth", word: "МОТЫЛЕК", illustration: .bundlePNG(name: "moth")),

        WordMatchPair(key: "table", word: "СТОЛ", illustration: .bundlePNG(name: "table")),
        WordMatchPair(key: "chair", word: "СТУЛ", illustration: .bundlePNG(name: "chair")),
        WordMatchPair(key: "sofa", word: "ДИВАН", illustration: .bundlePNG(name: "sofa")),
        WordMatchPair(key: "armchair", word: "КРЕСЛО", illustration: .bundlePNG(name: "armchair")),
        WordMatchPair(key: "wardrobe", word: "ШКАФ", illustration: .bundlePNG(name: "wardrobe")),
        WordMatchPair(key: "lamp", word: "ЛАМПА", illustration: .bundlePNG(name: "lamp")),
        WordMatchPair(key: "mirror", word: "ЗЕРКАЛО", illustration: .bundlePNG(name: "mirror")),
        WordMatchPair(key: "window", word: "ОКНО", illustration: .bundlePNG(name: "window")),
        WordMatchPair(key: "door", word: "ДВЕРЬ", illustration: .bundlePNG(name: "door")),
        WordMatchPair(key: "carpet", word: "КОВЕР", illustration: .bundlePNG(name: "carpet")),

        WordMatchPair(key: "guitar", word: "ГИТАРА", illustration: .bundlePNG(name: "guitar")),
        WordMatchPair(key: "violin", word: "СКРИПКА", illustration: .bundlePNG(name: "violin")),
        WordMatchPair(key: "trumpet", word: "ТРУБА", illustration: .bundlePNG(name: "trumpet")),
        WordMatchPair(key: "saxophone", word: "САКСОФОН", illustration: .bundlePNG(name: "saxophone")),
        WordMatchPair(key: "accordion", word: "ГАРМОШКА", illustration: .bundlePNG(name: "accordion")),
        WordMatchPair(key: "tambourine", word: "БУБЕН", illustration: .bundlePNG(name: "tambourine")),
        WordMatchPair(key: "microphone", word: "МИКРОФОН", illustration: .bundlePNG(name: "microphone")),
        WordMatchPair(key: "headphones", word: "НАУШНИКИ", illustration: .bundlePNG(name: "headphones")),
        WordMatchPair(key: "bell", word: "КОЛОКОЛЬЧИК", illustration: .bundlePNG(name: "bell")),
        WordMatchPair(key: "whistle", word: "СВИСТОК", illustration: .bundlePNG(name: "whistle")),

        WordMatchPair(key: "bench", word: "СКАМЕЙКА", illustration: .bundlePNG(name: "bench")),
        WordMatchPair(key: "fountain", word: "ФОНТАН", illustration: .bundlePNG(name: "fountain")),
        WordMatchPair(key: "fence", word: "ЗАБОР", illustration: .bundlePNG(name: "fence")),
        WordMatchPair(key: "gate", word: "ВОРОТА", illustration: .bundlePNG(name: "gate")),
        WordMatchPair(key: "swing", word: "КАЧЕЛИ", illustration: .bundlePNG(name: "swing")),
        WordMatchPair(key: "slide", word: "ГОРКА", illustration: .bundlePNG(name: "slide")),
        WordMatchPair(key: "sandbox", word: "ПЕСОЧНИЦА", illustration: .bundlePNG(name: "sandbox")),
        WordMatchPair(key: "shovel", word: "ЛОПАТКА", illustration: .bundlePNG(name: "shovel")),
        WordMatchPair(key: "rake", word: "ГРАБЛИ", illustration: .bundlePNG(name: "rake")),
        WordMatchPair(key: "computer", word: "КОМПЬЮТЕР", illustration: .bundlePNG(name: "computer")),

        WordMatchPair(key: "laptop", word: "НОУТБУК", illustration: .bundlePNG(name: "laptop")),
        WordMatchPair(key: "smartphone", word: "ТЕЛЕФОН", illustration: .bundlePNG(name: "smartphone")),
        WordMatchPair(key: "camera", word: "ФОТОАППАРАТ", illustration: .bundlePNG(name: "camera")),
        WordMatchPair(key: "television", word: "ТЕЛЕВИЗОР", illustration: .bundlePNG(name: "television")),
        WordMatchPair(key: "radio", word: "РАДИО", illustration: .bundlePNG(name: "radio")),
        WordMatchPair(key: "fan", word: "ВЕНТИЛЯТОР", illustration: .bundlePNG(name: "fan")),
        WordMatchPair(key: "vacuum", word: "ПЫЛЕСОС", illustration: .bundlePNG(name: "vacuum")),
        WordMatchPair(key: "refrigerator", word: "ХОЛОДИЛЬНИК", illustration: .bundlePNG(name: "refrigerator")),
        WordMatchPair(key: "pizza", word: "ПИЦЦА", illustration: .bundlePNG(name: "pizza")),
        WordMatchPair(key: "burger", word: "БУРГЕР", illustration: .bundlePNG(name: "burger")),

        WordMatchPair(key: "fries", word: "КАРТОШКА ФРИ", illustration: .bundlePNG(name: "fries")),
        WordMatchPair(key: "donut", word: "ПОНЧИК", illustration: .bundlePNG(name: "donut")),
        WordMatchPair(key: "cupcake", word: "КЕКС", illustration: .bundlePNG(name: "cupcake")),
        WordMatchPair(key: "pretzel", word: "КРЕНДЕЛЬ", illustration: .bundlePNG(name: "pretzel")),
        WordMatchPair(key: "popcorn", word: "ПОПКОРН", illustration: .bundlePNG(name: "popcorn")),
        WordMatchPair(key: "sandwich", word: "БУТЕРБРОД", illustration: .bundlePNG(name: "sandwich")),
        WordMatchPair(key: "hotdog", word: "ХОТ-ДОГ", illustration: .bundlePNG(name: "hotdog")),
        WordMatchPair(key: "croissant", word: "КРУАССАН", illustration: .bundlePNG(name: "croissant")),
        WordMatchPair(key: "helmet", word: "КАСКА", illustration: .bundlePNG(name: "helmet")),
        WordMatchPair(key: "toothbrush", word: "ЗУБНАЯ ЩЕТКА", illustration: .bundlePNG(name: "toothbrush")),

        WordMatchPair(key: "tent", word: "ПАЛАТКА", illustration: .bundlePNG(name: "tent")),
        WordMatchPair(key: "suitcase", word: "ЧЕМОДАН", illustration: .bundlePNG(name: "suitcase")),
        WordMatchPair(key: "binoculars", word: "БИНОКЛЬ", illustration: .bundlePNG(name: "binoculars")),
        WordMatchPair(key: "lantern", word: "ФОНАРЬ", illustration: .bundlePNG(name: "lantern")),
        WordMatchPair(key: "crown", word: "КОРОНА", illustration: .bundlePNG(name: "crown")),
        WordMatchPair(key: "cactus", word: "КАКТУС", illustration: .bundlePNG(name: "cactus")),
        WordMatchPair(key: "pineapple", word: "АНАНАС", illustration: .bundlePNG(name: "pineapple")),
        WordMatchPair(key: "samovar", word: "САМОВАР", illustration: .bundlePNG(name: "samovar")),
        WordMatchPair(key: "rollerskates", word: "РОЛИКИ", illustration: .bundlePNG(name: "rollerskates")),
        WordMatchPair(key: "thermos", word: "ТЕРМОС", illustration: .bundlePNG(name: "thermos"))
    ]

    static let all = primerSet + extendedSet + supplementalSet

    static func defaultPool() -> [WordMatchPair] {
        ProcessInfo.processInfo.arguments.contains("UITestSmallWordSet") ? primerSet : all
    }

    static func readingPracticePool() -> [WordMatchPair] {
        let source = defaultPool()
        let filtered = source.filter(isSuitableForReadAloud)
        return filtered.isEmpty ? primerSet : filtered
    }

    private static func isSuitableForReadAloud(_ pair: WordMatchPair) -> Bool {
        !pair.word.contains(" ") && !pair.word.contains("-")
    }
}
